name: Format and Lint

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt --upgrade
          pip install autopep8

      - name: Format code with autopep8
        run: autopep8 --in-place --recursive --aggressive --aggressive .

      - name: Commit and push changes if necessary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git diff --quiet || (
            git add .
            git commit -m "Format code with autopep8"
            git push
          )
